//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GongZuo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GongZuo()
        {
            this.XueShengQiuZhi = new HashSet<XueShengQiuZhi>();
            this.ShangJiaZhaoPin = new HashSet<ShangJiaZhaoPin>();
            this.XueShengZhaoPin = new HashSet<XueShengZhaoPin>();
            this.ShouCangGongZuo = new HashSet<ShouCangGongZuo>();
            this.HaoYouXinXi = new HashSet<HaoYouXinXi>();
        }
    
        public int id { get; set; }
        public string shangjialeixing { get; set; }
        public string qiuzhi { get; set; }
        public Nullable<System.DateTime> shijian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XueShengQiuZhi> XueShengQiuZhi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShangJiaZhaoPin> ShangJiaZhaoPin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XueShengZhaoPin> XueShengZhaoPin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShouCangGongZuo> ShouCangGongZuo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaoYouXinXi> HaoYouXinXi { get; set; }
    }
}
