//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaoYouXinXi
    {
        public int id { get; set; }
        public string name { get; set; }
        public int xueshengid { get; set; }
        public string liaotian { get; set; }
        public System.DateTime jiaoyoushijian { get; set; }
        public Nullable<int> zuduicishu { get; set; }
        public Nullable<int> zuduigongzuo { get; set; }
    
        public virtual GongZuo GongZuo { get; set; }
        public virtual XueShengXinXi XueShengXinXi { get; set; }
    }
}
