//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JianZhiEntities : DbContext
    {
        public JianZhiEntities()
            : base("name=JianZhiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GongZuo> GongZuo { get; set; }
        public virtual DbSet<HaoYouXinXi> HaoYouXinXi { get; set; }
        public virtual DbSet<KeCheng> KeCheng { get; set; }
        public virtual DbSet<ShangJiaGuangGao> ShangJiaGuangGao { get; set; }
        public virtual DbSet<ShangJiaJiaoYiJiLu> ShangJiaJiaoYiJiLu { get; set; }
        public virtual DbSet<ShangJiaXinXi> ShangJiaXinXi { get; set; }
        public virtual DbSet<ShangJiaZhaoPin> ShangJiaZhaoPin { get; set; }
        public virtual DbSet<ShouCangGongZuo> ShouCangGongZuo { get; set; }
        public virtual DbSet<ShouCangShangJia> ShouCangShangJia { get; set; }
        public virtual DbSet<XueShengJiaoYiJiLu> XueShengJiaoYiJiLu { get; set; }
        public virtual DbSet<XueShengQiuZhi> XueShengQiuZhi { get; set; }
        public virtual DbSet<XueShengXinXi> XueShengXinXi { get; set; }
        public virtual DbSet<XueShengZhaoPin> XueShengZhaoPin { get; set; }
    }
}
