//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShangJiaXinXi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShangJiaXinXi()
        {
            this.ShangJiaGuangGao = new HashSet<ShangJiaGuangGao>();
            this.ShangJiaJiaoYiJiLu = new HashSet<ShangJiaJiaoYiJiLu>();
            this.XueShengQiuZhi = new HashSet<XueShengQiuZhi>();
            this.ShouCangShangJia = new HashSet<ShouCangShangJia>();
        }
    
        public int id { get; set; }
        public string gongsi { get; set; }
        public string fuzeren { get; set; }
        public string zhengjianhao { get; set; }
        public byte[] head_image { get; set; }
        public string phone { get; set; }
        public string pass { get; set; }
        public byte[] xukezheng { get; set; }
        public string huiyuan { get; set; }
        public string dizhi { get; set; }
        public string tongguo { get; set; }
        public string leixing { get; set; }
        public int zaopincishu { get; set; }
        public int xingyong { get; set; }
        public string qq { get; set; }
        public string weixin { get; set; }
        public System.DateTime day_login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShangJiaGuangGao> ShangJiaGuangGao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShangJiaJiaoYiJiLu> ShangJiaJiaoYiJiLu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XueShengQiuZhi> XueShengQiuZhi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShouCangShangJia> ShouCangShangJia { get; set; }
    }
}
