//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShouCangShangJia
    {
        public int id { get; set; }
        public string name { get; set; }
        public int xueshengid { get; set; }
        public int shangjiaid { get; set; }
        public System.DateTime shijian { get; set; }
        public string shixiao { get; set; }
    
        public virtual ShangJiaXinXi ShangJiaXinXi { get; set; }
        public virtual XueShengXinXi XueShengXinXi { get; set; }
    }
}
