//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XueShengZhaoPin
    {
        public int id { get; set; }
        public int gongzuoid { get; set; }
        public string name { get; set; }
        public string yaoqiu { get; set; }
        public string neirong { get; set; }
        public string xiangqing { get; set; }
        public Nullable<System.DateTime> fabushijian { get; set; }
        public string yingpinqingkuang { get; set; }
        public string luyongqingkuang { get; set; }
        public string chengliqingkuang { get; set; }
        public string zhaoman { get; set; }
    
        public virtual GongZuo GongZuo { get; set; }
    }
}
