//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XueShengXinXi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XueShengXinXi()
        {
            this.HaoYouXinXi = new HashSet<HaoYouXinXi>();
            this.KeCheng = new HashSet<KeCheng>();
            this.ShouCangGongZuo = new HashSet<ShouCangGongZuo>();
            this.ShouCangShangJia1 = new HashSet<ShouCangShangJia>();
            this.XueShengJiaoYiJiLu = new HashSet<XueShengJiaoYiJiLu>();
            this.XueShengQiuZhi = new HashSet<XueShengQiuZhi>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public byte[] head_image { get; set; }
        public string phone { get; set; }
        public string pass { get; set; }
        public string huiyuan { get; set; }
        public string dizhi { get; set; }
        public Nullable<System.DateTime> chushengriqi { get; set; }
        public string leixing { get; set; }
        public string shoucangshangjia { get; set; }
        public string 收藏gongzuo { get; set; }
        public Nullable<int> cishu { get; set; }
        public int xingyong { get; set; }
        public string shangjia { get; set; }
        public string qq { get; set; }
        public string weixin { get; set; }
        public System.DateTime day_login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaoYouXinXi> HaoYouXinXi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeCheng> KeCheng { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShouCangGongZuo> ShouCangGongZuo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShouCangShangJia> ShouCangShangJia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XueShengJiaoYiJiLu> XueShengJiaoYiJiLu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XueShengQiuZhi> XueShengQiuZhi { get; set; }
    }
}
