//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XueShengQiuZhi
    {
        public int id { get; set; }
        public int gongzuoid { get; set; }
        public string name { get; set; }
        public string titie { get; set; }
        public string xinxi { get; set; }
        public System.DateTime fabushijian { get; set; }
        public int xueshengid { get; set; }
        public int shangjiaid { get; set; }
        public string zhongyishangjia { get; set; }
        public string xuanze商家 { get; set; }
        public Nullable<System.DateTime> chenglishijian { get; set; }
    
        public virtual GongZuo GongZuo { get; set; }
        public virtual ShangJiaXinXi ShangJiaXinXi { get; set; }
        public virtual XueShengXinXi XueShengXinXi { get; set; }
    }
}
